name: Change Freeze Times

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

    branches:
      - main

jobs:
  no_change_freeze_merge:
    name: Out of Hours Check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Block merge during specified times
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIMEZONE: "Australia/Sydney"
          RESTRICTED_TIMES: >
            {
              "weekly": [
                {
                  "days": ["wed", "thu", "fri", "sat", "sun"],
                  "intervals": [[0, 8.5], [16.5, 24]]
                }
              ],
              "dates": [
                {
                  "date": "2023-12-25",
                  "intervals": [[0, 24]]
                }
              ]
            }
          CUSTOM_MESSAGE: "The PR can't be merged during the change freeze, which is due to the organization's policy"
        run: no-change-freeze-merge
