name: Rerun Checks on Change Freeze times

on:
  schedule:
    - cron: '30 22 * * 0-3' # Runs at 10:30 PM UTC, Sunday to Wednesday (which is 8:30 AM Monday to Thursday in Sydney) # Change Freeze End time for Weekdays
    - cron: '30 6 * * 1-4' # Runs at 6:30 AM UTC, Monday to Thursday (which is 4:30 PM Monday to Thursday in Sydney) # Change Freeze Start time for Weekdays
    - cron: '55 1 * * 3' # Runs at 6:30 AM UTC, Monday to Thursday (which is 4:30 PM Monday to Thursday in Sydney) # Change Freeze Start time for Weekdays

jobs:
  rerun_checks:
    runs-on: ubuntu-latest
    name: Rerun specified checks
    steps:
      - name: Rerun Checks
        uses: shqear93/rerun-checks@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          check-names: "check-change-freeze" # Replace with the names of the jobs you want to rerun
